# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d408ZVgq7Dgwk_z13Dz4PaQQEPpT8Pu6
"""

log = '''
[2025-02-20 14:32:10] INFO - Agent Response: "Hello! How can I help you today?"
[2025-02-20 14:33:15] ERROR - Model Timeout after 5000ms
[2025-02-20 14:34:02] INFO - Agent Response: "I'm sorry, I didn't understand that."
'''

import re
from collections import defaultdict, Counter

log_patttern = re.compile(r"\[(.*?)\]\s+(\w+)\s+-\s+(.*)")
agent_response_pattern = re.compile(r'Agent Response: "(.*?)"')

message_counts = defaultdict(int)
agent_responses = Counter()
error_messages = Counter()

for line in log.strip().splitlines():
  match_p = log_patttern.match(line.strip())
  if not match_p:
    continue

  _, level, message = match_p.groups()
  message_counts[level] += 1

  if level == "INFO":
    response_match = agent_response_pattern.search(message)
    if response_match:
      response_text = response_match.group(1)
      agent_responses[response_text] += 1

  if level == "ERROR":
    error_messages[message.strip()] += 1

"""Example Output:
Log Summary:
- INFO messages: 42
- ERROR messages: 8
- WARNING messages: 5

Top 3 AI Responses:
1. "Hello! How can I help you today?" (12 times)
2. "I'm sorry, I didn't understand that." (7 times)
3. "Please provide more details." (5 times)

Most Common Errors:
1. Model Timeout after 5000ms (3 times)
2. API Connection Failure (2 times)
"""

print("Log Summary:")
print(f"- INFO messages: {message_counts['INFO']}")
print(f"- ERROR messages: {message_counts['ERROR']}")
print(f"- WARNING messages: {message_counts['WARNING']}")

print("Top 3 AI Responses:")
for i, (response, count) in enumerate(agent_responses.most_common(3), 1):
  print(f"{i}. \"{response}\" ({count} times)")

print("\nMost Common Errors:")
for i, (err, count) in enumerate(error_messages.most_common(3), 1):
  print(f"{i}. {err} ({count} times)")